//
// Created by os on 8/29/25.
//

#ifndef PROJECT_BASE_V1_1_GETTHREADID_TEST_HPP
#define PROJECT_BASE_V1_1_GETTHREADID_TEST_HPP
void GetThreadId_test();
#endif //PROJECT_BASE_V1_1_GETTHREADID_TEST_HPP
