//
// Created by os on 8/30/25.
//

#ifndef PROJECT_BASE_V1_1_PRIORITYSEMAPHORE_TEST_HPP
#define PROJECT_BASE_V1_1_PRIORITYSEMAPHORE_TEST_HPP


void PrioritySemaphore_test();


#endif //PROJECT_BASE_V1_1_PRIORITYSEMAPHORE_TEST_HPP
